#!/bin/bash
# setup_vfio.sh -- Interactive VFIO setup: kernel params + modprobe config
# Usage: sudo bash scripts/setup_vfio.sh
#
# Detects your CPU vendor (Intel/AMD), asks which GPU to pass through,
# and writes /etc/default/grub and /etc/modprobe.d/vfio.conf for you.
#
# IMPORTANT (AMD RX 9000+): use --late-bind to skip kernel-parameter binding
# and only configure the modprobe file. RX 9000 series MUST be initialized
# by amdgpu first -- bind dynamically with scripts/bind_vfio.sh instead.
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

usage() {
    echo "Usage: sudo bash $0 [--late-bind] [--grub FILE] [--modprobe FILE]"
    echo ""
    echo "  --late-bind   AMD RX 9000+ dynamic binding (skip kernel params)"
    echo "  --grub FILE   Path to GRUB defaults (default: /etc/default/grub)"
    echo "  --modprobe F  Path to vfio modprobe file (default: /etc/modprobe.d/vfio.conf)"
    exit 1
}

LATE_BIND=false
GRUB_FILE="/etc/default/grub"
MODPROBE_FILE="/etc/modprobe.d/vfio.conf"

while [ $# -gt 0 ]; do
    case "$1" in
        --late-bind)  LATE_BIND=true; shift ;;
        --grub)       GRUB_FILE="$2"; shift 2 ;;
        --modprobe)   MODPROBE_FILE="$2"; shift 2 ;;
        -h|--help)    usage ;;
        *)            echo "Unknown option: $1"; usage ;;
    esac
done

if [ "$(id -u)" -ne 0 ]; then
    echo -e "${RED}Run as root: sudo bash $0${NC}"
    exit 1
fi

echo -e "${CYAN}========================================${NC}"
echo -e "${CYAN}  Interactive VFIO Setup${NC}"
echo -e "${CYAN}========================================${NC}"
echo ""

# --- Detect CPU vendor ---
if grep -q -i "GenuineIntel" /proc/cpuinfo; then
    CPU_VENDOR="intel"
    IOMMU_PARAM="intel_iommu=on"
elif grep -q -i "AuthenticAMD" /proc/cpuinfo; then
    CPU_VENDOR="amd"
    IOMMU_PARAM="amd_iommu=on"
else
    echo -e "${RED}Could not detect CPU vendor.${NC}"
    exit 1
fi
echo -e "  CPU vendor: ${GREEN}${CPU_VENDOR}${NC}"

# --- Show GPUs ---
echo ""
echo -e "${CYAN}Detected VGA/3D controllers:${NC}"
lspci -nn | grep -iE 'vga|3d' | while IFS= read -r line; do
    PCI=$(echo "$line" | awk '{print $1}')
    ID=$(lspci -n -s "$PCI" | grep -oE '\[[0-9a-f]{4}:[0-9a-f]{4}\]' | head -1 | tr -d '[]')
    echo "    $line"
    echo "        ID: $ID"
done

echo ""
echo -e "${YELLOW}Enter the vendor:device IDs of the GPU to pass through,"
echo -e "comma-separated (e.g. 10de:1af2,10de:1af9).${NC}"
read -r -p "  GPU IDs: " GPU_IDS

if [ -z "$GPU_IDS" ]; then
    echo -e "${RED}No IDs entered. Aborting.${NC}"
    exit 1
fi

# --- Backup existing files ---
if [ -f "$GRUB_FILE" ]; then
    cp "$GRUB_FILE" "${GRUB_FILE}.bak"
    echo -e "${GREEN}Backed up $GRUB_FILE -> ${GRUB_FILE}.bak${NC}"
fi
if [ -f "$MODPROBE_FILE" ]; then
    cp "$MODPROBE_FILE" "${MODPROBE_FILE}.bak"
    echo -e "${GREEN}Backed up $MODPROBE_FILE -> ${MODPROBE_FILE}.bak${NC}"
fi

# --- Write modprobe config ---
mkdir -p "$(dirname "$MODPROBE_FILE")"
cat > "$MODPROBE_FILE" <<EOF
# Auto-generated by setup_vfio.sh
options vfio-pci ids=${GPU_IDS}
EOF

if $LATE_BIND; then
    echo ""
    echo -e "${YELLOW}[AMD late-bind mode] Skipping kernel-parameter binding.${NC}"
    echo -e "${YELLOW}Use scripts/bind_vfio.sh or a libvirt hook before starting the VM.${NC}"
else
    # --- Write GRUB config ---
    if grep -q "^GRUB_CMDLINE_LINUX_DEFAULT" "$GRUB_FILE"; then
        sed -i "s|^GRUB_CMDLINE_LINUX_DEFAULT=.*|GRUB_CMDLINE_LINUX_DEFAULT=\"quiet splash ${IOMMU_PARAM} iommu=pt vfio-pci.ids=${GPU_IDS} rd.driver.pre=vfio-pci\"|" "$GRUB_FILE"
    else
        echo "GRUB_CMDLINE_LINUX_DEFAULT=\"quiet splash ${IOMMU_PARAM} iommu=pt vfio-pci.ids=${GPU_IDS} rd.driver.pre=vfio-pci\"" >> "$GRUB_FILE"
    fi
    echo -e "${GREEN}Updated ${GRUB_FILE}${NC}"
fi

echo ""
echo -e "${CYAN}========================================${NC}"
echo -e "${CYAN}  Next Steps${NC}"
echo -e "${CYAN}========================================${NC}"
echo ""
echo "  1. Rebuild the bootloader / initramfs:"
echo "       Debian/Ubuntu: sudo update-initramfs -u && sudo update-grub"
echo "       Arch (GRUB):   sudo mkinitcpio -P && sudo grub-mkconfig -o /boot/grub/grub.cfg"
echo "       Fedora:        sudo dracut -f && sudo grub2-mkconfig -o /boot/grub2/grub.cfg"
echo "       systemd-boot:  sudo bootctl update"
echo "  2. Reboot."
echo "  3. Verify: bash scripts/check_vfio_binding.sh"
echo ""
if $LATE_BIND; then
    echo "  4. Before starting the VM: sudo bash scripts/bind_vfio.sh unbind 0000:XX:XX.X 0000:XX:XX.X"
    echo "     (see README.md section 6a for the full dynamic-binding workflow)"
fi
echo ""
